title: "내 블로그 제목"
author: "작성자 이름"
description: "블로그에 대한 짧은 설명입니다."
url: "https://arim0317-dot.github.io"
baseurl: "/my-blog"

theme: minima

minima:
  skin: dark
  date_format: "%Y년 %m월 %d일"
  social_links:
    - { platform: github, user_url: "https://github.com/arim0317-dot" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /:title/